__include__: [
  '../dataset/gr_detection_pilot.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
  '../runtime.yml',
]


output_dir: ./output/rtdetrv2_r18vd_50e_gr_pilot_tmp


PResNet:
  depth: 18
  freeze_at: -1
  freeze_norm: False
  pretrained: True


HybridEncoder:
  in_channels: [128, 256, 512]
  hidden_dim: 256
  expansion: 0.5


RTDETRTransformerv2:
  num_layers: 3


epoches: 50 

optimizer:
  type: AdamW
  params:
    - 
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

eval_spatial_size: [1280, 1280]

train_dataloader: 
  dataset: 
    transforms:
      ops:
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: RandomZoomOut, fill: 0}
        - {type: RandomIoUCrop, p: 0.8}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: RandomHorizontalFlip}
        - {type: Resize, size: [1280, 1280], }
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}   
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}    
      policy:
        epoch: 45
  collate_fn:
    scales: ~

  total_batch_size: 6

val_dataloader:
  dataset: 
    transforms:
      ops: 
        - {type: Resize, size: [1280, 1280]}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}   
  total_batch_size: 12