__include__: [
  '../dataset/gr_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]


HybridEncoder:
  expansion: 0.5


RTDETRTransformerv2:
  eval_idx: 2 # use 3th decoder layer to eval


epoches: 84

optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.00001
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001

eval_spatial_size: [1280, 1280]

train_dataloader: 
  dataset: 
    transforms:
      ops:
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: RandomZoomOut, fill: 0}
        - {type: RandomIoUCrop, p: 0.8}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: RandomHorizontalFlip}
        - {type: Resize, size: [1280, 1280], }
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}   
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}    
      policy:
        epoch: 81
  collate_fn:
    scales: ~
    stop_epoch: 81
  total_batch_size: 4

val_dataloader:
  dataset: 
    transforms:
      ops: 
        - {type: Resize, size: [1280, 1280]}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}   
  total_batch_size: 16