__include__: [
  '../dataset/gr_detection.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
  '../runtime.yml',
]


output_dir: ./output/rtdetrv2_r18vd_120e_ir_1ch
num_classes: 8 # Has to be actual number of classes + 1
epoches: 120

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: ./data
    ann_file: /home/ros/visionai_platform/data/public/massmind/coco_labels/train.mapped.json
    return_masks: False
    transforms:
      type: Compose
      ops:
        - {type: RandomZoomOut, fill: 0}
        - {type: RandomIoUCrop, p: 0.8}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: RandomHorizontalFlip}
        - {type: Resize, size: [640, 640], }
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: ConvertPILImage, dtype: 'float32', scale: True, single_channel: True}   
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}    
      policy:
        epoch: 117
  collate_fn:
    type: BatchImageCollateFuncion  
    scales: ~
  total_batch_size: 28
  shuffle: True
  num_workers: 4
  drop_last: True 

val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: ./data
    ann_file: /home/ros/visionai_platform/data/public/massmind/coco_labels/test.mapped.json
    return_masks: False
    transforms:
      type: Compose
      ops: 
        - {type: Resize, size: [640, 640]}
        - {type: ConvertPILImage, dtype: 'float32', scale: True, single_channel: True}   
  total_batch_size: 32
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFuncion  

PResNet:
  depth: 18
  freeze_at: 0
  freeze_norm: False
  pretrained: False
  image_channels: 1


HybridEncoder:
  in_channels: [128, 256, 512]
  hidden_dim: 256
  expansion: 0.5


RTDETRTransformerv2:
  num_layers: 3

optimizer:
  type: AdamW
  params:
    - 
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

eval_spatial_size: [640, 640]